version: "2"

services:
  snapcast:
    container_name: snapcast
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SPOTIFY_BITRATE: 320
      SPOTIFY_NAME: Snapcast
      SNAPCAST_HOST: localhost
    networks:
      macvlan:
        ipv4_address: 192.168.2.100
     
networks:
  macvlan:
    external: true
